name: Daily Stock and Periodic Job Report

on:
  schedule:
    # Runs daily at 9 PM UTC (4 PM EST - after market close)
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install yfinance pandas requests
        
    - name: Load references
      id: load-ref
      uses: actions/cache@v3
      with:
        path: references.json
        key: ref-${{ runner.os }}-${{ hashFiles('smart_report.py') }}
        
    - name: Run report
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      run: python smart_report.py
      
    - name: Save references
      if: always()
      uses: actions/cache@v3
      with:
        path: references.json
        key: ref-${{ runner.os }}-${{ hashFiles('smart_report.py') }}
